name: ClearVision
author: Zerthox
description: ClearVision is an easily customizable, auto-updating theme for Discord.

exclude:
    - README.md
    - LICENSE.md
    - Gemfile

sass:
    sass_dir: /
    style: compressed