main-color: "#2780e6"
hover-color: "#1e63b3"
online-color: "#43b581"
idle-color: "#faa61a"
dnd-color: "#982929"
offline-color: "#808080"
background-image: https://zerthox.github.io/ClearVision/images/sapphire.jpg
background-brightness: 100%
background-blur: 0px
load1: '""'
load2: '""'
load3: '""'